### PR TITLE
web app for the cpp python interface

### PR DESCRIPTION
**Pull request by bbartling**
let me know your thoughts if it works Okay on your end. There is a `web_app` sub directory.

I am also really curious to learn where to add in Lang Chain, like is this is something that could just be easily added into the web app code:

- https://python.langchain.com/docs/modules/memory/how_to/adding_memory

What looks odd is all the examples only show `llm=OpenAI()` to me what looks like an `OpenAI` only LLM? Any idea if there is just a simply conversation summary Lang Chain feature? Would love to figure this out by coding some examples. If you are familiar with Lang Chain if you made an example I could build it into the web app too.

### CODE REVIEW

**Comment by bbartling** [comment]
Another thing is the web app code assumes the model is just downloaded into directory. `MODEL_PATH = "../ggml-vicuna-7b-1.1-q4_1.bin"`

**Comment by awinml** [comment]
LangChain is a wrapper on top of multiple LLM frameworks. Memory is very important for ChatBots, so that is something that you should consider adding to the app. 

You can implement the [memory](https://python.langchain.com/docs/modules/memory/how_to/adding_memory) using the example, just by instantiating a Llama.cpp model instead of OpenAI.

You can look at the [Llama.cpp integration](https://python.langchain.com/docs/integrations/llms/llamacpp) with LangChain for an example on how to do that. It is very similar to the code you already have.

**Comment by awinml** [comment]
In the meantime, I will put together a simple example using this idea that you can use for the app.

> LangChain is a wrapper on top of multiple LLM frameworks. Memory is very important for ChatBots, so that is something that you should consider adding to the app.
> 
> You can implement the [memory](https://python.langchain.com/docs/modules/memory/how_to/adding_memory) using the example, just by instantiating a Llama.cpp model instead of OpenAI.
> 
> You can look at the [Llama.cpp integration](https://python.langchain.com/docs/integrations/llms/llamacpp) with LangChain for an example on how to do that. It is very similar to the code you already have.

**Comment by bbartling** [comment]
sounds great thanks!

**Pull request closed without merging**
